{{- if .Values.juiceShopCleanup.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: 'cleanup-job'
spec:
  schedule: {{ .Values.juiceShopCleanup.cron }}
  successfulJobsHistoryLimit: {{ .Values.juiceShopCleanup.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.juiceShopCleanup.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: 'cleanup-job'
            helm.sh/chart: {{ include "multi-juicer.chart" . }}
        spec:
          serviceAccountName: 'juice-cleaner'
          {{- with .Values.juiceShopCleanup.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
            - image: '{{ .Values.juiceShopCleanup.repository }}:{{ .Values.juiceShopCleanup.tag | default (printf "v%s" .Chart.Version) }}'
              imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
              name: 'cleanup-job'
              env:
                - name: NAMESPACE
                  value: {{ .Release.Namespace | quote }}
                - name: MAX_INACTIVE_DURATION
                  value: {{ .Values.juiceShopCleanup.gracePeriod }}
          restartPolicy: Never
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.juiceShopCleanup.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.juiceShopCleanup.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
{{- end }}
