apiVersion: v1
kind: Secret
metadata:
  name: juice-balancer-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "multi-juicer.chart" . }}
type: Opaque
data:
  {{- if .Values.balancer.cookieParserSecret }}
  cookieParserSecret: {{ .Values.balancer.cookieParserSecret | b64enc | quote }}
  {{- else }}
  cookieParserSecret: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
  {{- if .Values.balancer.adminPassword }}
  adminPassword: {{ .Values.balancer.adminPassword | b64enc | quote }}
  {{- else }}
  adminPassword: {{ randAlphaNum 8 | upper | b64enc | quote }}
  {{- end }}