apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: juice-balancer
  labels:
    helm.sh/chart: {{ include "multi-juicer.chart" . }}
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'create', 'list', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['services']
    verbs: ['get', 'create', 'delete']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['pods']
    verbs: ['get', 'list', 'delete']