apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'juice-balancer'
  labels:
    app: 'juice-balancer'
    helm.sh/chart: {{ include "multi-juicer.chart" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 'juice-balancer'
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/juice-balancer-config-map.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/juice-balancer-secret.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: 'juice-balancer'
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: juice-balancer
      containers:
        - name: juice-balancer
          image: '{{ .Values.balancer.repository }}:{{ .Values.balancer.tag }}'
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /balancer/
              port: http
          readinessProbe:
            httpGet:
              path: /balancer/
              port: http
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
            - name: COOKIEPARSER_SECRET
              valueFrom:
                secretKeyRef:
                  name: juice-balancer-secret
                  key: cookieParserSecret
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: juice-balancer-secret
                  key: adminPassword
          volumeMounts:
            - name: config-volume
              mountPath: /home/app/config/
          resources:
            {{- toYaml .Values.balancer.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: juice-balancer-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.balancer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.balancer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
