apiVersion: v2
name: multi-juicer
description: Run Multi User "Capture the Flags" or Security Trainings with OWASP Juice Shop
icon: https://raw.githubusercontent.com/juice-shop/multi-juicer/main/images/multijuicer-icon-only.png

home: https://github.com/juice-shop/multi-juicer
sources:
  - https://github.com/juice-shop/multi-juicer

keywords:
  - security
  - juice-shop
  - owasp
  - capture-the-flag
  - ctf-platform
  - hacking
  - kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# both chart and app version are automatically set by the release workflow, these are just placeholders
version: 8.0.0-local-unreleased
appVersion: 8.0.0-local-unreleased

dependencies: []
