{{- if and .Values.balancer.metrics.enabled .Values.balancer.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: juice-shops
  labels:
    {{- include "multi-juicer.juice-shop.labels" . | nindent 4 }}
spec:
  targetLabels:
    - team
  selector:
    matchLabels:
      app.kubernetes.io/name: 'juice-shop'
      app.kubernetes.io/managed-by: {{ .Release.Name | quote }}
  endpoints:
    - targetPort: 3000
{{- end }}