apiVersion: apps/v1
kind: Deployment
metadata:
  name: wrongsecrets-balancer
  labels:
    app: wrongsecrets-balancer
    {{- include "wrongsecrets-ctf-party.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.balancer.replicas }}
  selector:
    matchLabels:
      {{- include "wrongsecrets-ctf-party.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/wrongsecrets-balancer/config-map.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/wrongsecrets-balancer/secret.yaml") . | sha256sum }}
      labels:
        app: wrongsecrets-balancer
        {{- include "wrongsecrets-ctf-party.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: wrongsecrets-balancer
      containers:
        - name: {{ .Chart.Name }}
          image: '{{ .Values.balancer.repository }}:{{ .Values.balancer.tag | default (printf "v%s" .Chart.Version) }}'
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /balancer/
              port: http
          readinessProbe:
            httpGet:
              path: /balancer/
              port: http
          env:
            - name: REACT_APP_MOVING_GIF_LOGO
              value: {{ .Values.balancer.env.REACT_APP_MOVING_GIF_LOGO }}
            - name: REACT_APP_ACCESS_PASSWORD
              value: {{ .Values.balancer.env.REACT_APP_ACCESS_PASSWORD }}
            - name: REACT_APP_HEROKU_WRONGSECRETS_URL
              value: {{ .Values.balancer.env.REACT_APP_HEROKU_WRONGSECRETS_URL }}
            - name: REACT_APP_CTFD_URL
              value: {{ .Values.balancer.env.REACT_APP_CTFD_URL }}
            - name: REACT_APP_S3_BUCKET_URL
              value: {{ .Values.balancer.env.REACT_APP_S3_BUCKET_URL }}
            - name: K8S_ENV
              value: {{ .Values.balancer.env.K8S_ENV }}
            - name: IRSA_ROLE
              value: {{ .Values.balancer.env.IRSA_ROLE }} #REPLACE WITH THE ACTUAL AWS ROLE IF IN AWS MODE
            - name: WRONGSECRETS_TAG
              value: {{ .Values.wrongsecrets.tag}}
            - name: WRONGSECRETS_DESKTOP_TAG
              value: {{ .Values.virtualdesktop.tag }}
            - name: REACT_APP_CREATE_TEAM_HMAC_KEY
              value: hardcodedkey
            - name: SECRETS_MANAGER_SECRET_ID_1
              value: {{ .Values.balancer.env.SECRETS_MANAGER_SECRET_ID_1 }}
            - name: SECRETS_MANAGER_SECRET_ID_2
              value: {{ .Values.balancer.env.SECRETS_MANAGER_SECRET_ID_2 }}
            - name: CHALLENGE33_VALUE
              value: {{ .Values.balancer.env.CHALLENGE33_VALUE }}
            - name: COOKIEPARSER_SECRET
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: cookieParserSecret
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: adminPassword
            {{- if .Values.balancer.metrics.enabled }}
            - name: METRICS_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: metricsBasicAuthUsername
            - name: METRICS_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wrongsecrets-balancer-secret
                  key: metricsBasicAuthPassword
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
              add:
                - CAP_NET_ADMIN
                - CAP_NET_BIND_SERVICE
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - name: config-volume
              mountPath: /home/app/config/
          resources:
            {{- toYaml .Values.balancer.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: wrongsecrets-balancer-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.balancer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.balancer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
