apiVersion: v1
kind: Secret
metadata:
  name: wrongsecrets-balancer-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "wrongsecrets-ctf-party.chart" . }}
type: Opaque
data:
  {{- if .Values.balancer.cookieParserSecret }}
  cookieParserSecret: {{ .Values.balancer.cookieParserSecret | b64enc | quote }}
  {{- else }}
  cookieParserSecret: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}
  {{- if .Values.balancer.basicAuth.adminPassword }}
  adminPassword: {{ .Values.balancer.basicAuth.adminPassword | b64enc | quote }}
  {{- else }}
  adminPassword: {{ randAlphaNum 8 | upper | b64enc | quote }}
  {{- end }}
  {{- if .Values.balancer.metrics.enabled }}
  metricsBasicAuthUsername: {{ .Values.balancer.metrics.basicAuth.username | b64enc | quote }}
  metricsBasicAuthPassword: {{ .Values.balancer.metrics.basicAuth.password | b64enc | quote }}
  {{- end }}
