apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'progress-watchdog'
  labels:
    app: 'progress-watchdog'
    helm.sh/chart: {{ include "wrongsecrets-ctf.chart" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: 'progress-watchdog'
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: 'progress-watchdog'
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: progress-watchdog
      {{- with .Values.progressWatchdog.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: progress-watchdog
          image: '{{ .Values.progressWatchdog.repository }}:{{ .Values.progressWatchdog.tag | default (printf "v%s" .Chart.Version) }}'
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            {{- toYaml .Values.progressWatchdog.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.progressWatchdog.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.progressWatchdog.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
