apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: progress-watchdog
  labels:
    helm.sh/chart: {{ include "wrongsecrets-ctf.chart" . }}
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'patch']
