on:
  release:
    types: [published]
name: "Publish Docker Images"
jobs:
  helmRelease:
    name: "Package Helm Chart"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install yq"
        run: |
          sudo snap install yq
      - name: "Patch Chart.yaml to the current released version"
        working-directory: helm/multi-juicer/
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          # Remove leading 'v' from git tag to create valid semver
          RELEASE_VERSION="${RELEASE_VERSION//v}"
          # patch the version & appVersion in the Chart.yaml to the release version
          yq eval -i '.version = "$RELEASE_VERSION", .appVersion = "RELEASE_VERSION"' Chart.yaml
      - uses: J12934/helm-gh-pages-action@v2.0.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          charts-folder: helm
          deploy-branch: gh-pages