on:
  release:
    types: [published]
name: "Publish Docker Images"
jobs:
  helmRelease:
    name: "Package Helm Chart"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Install yq"
        run: |
          sudo snap install yq
      - name: "Patch Chart.yaml to the current released version"
        working-directory: helm/wrongsecrets-ctf-party/
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          # Remove leading 'v' from git tag to create valid semver
          RELEASE_VERSION="${RELEASE_VERSION//v}"
          # patch the version & appVersion in the Chart.yaml to the release version
          yq eval -i ".version = \"$RELEASE_VERSION\", .appVersion = \"$RELEASE_VERSION\"" Chart.yaml
      - uses: J12934/helm-gh-pages-action@v2.0.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          charts-folder: helm
          deploy-branch: gh-pages
  dockerBuilds:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - progress-watchdog
          - cleaner
          - wrongsecrets-balancer
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: iteratec/${{ matrix.component }}
          tags: |
            type=semver,pattern={{raw}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
