on: [release]
name: 'Publish Docker Images'
jobs:
  helmRelease:
    name: 'Package Helm Chart'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@v1.0.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          charts-folder: helm
          deploy-branch: gh-pages
  progressWatchDog:
    name: ProgressWatchDog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build'n Push ProgressWatchDog
        uses: pangzineng/Github-Action-One-Click-Docker@bfb4a810c8cb823f4a87c24da145caa707e297e9
        env:
          DOCKER_IMAGE_NAME: juice-progress-watchdog
          DOCKER_NAMESPACE: iteratec
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./progress-watchdog/
  cleaner:
    name: Cleaner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build'n Push Cleaner
        uses: pangzineng/Github-Action-One-Click-Docker@bfb4a810c8cb823f4a87c24da145caa707e297e9
        env:
          DOCKER_IMAGE_NAME: juice-cleaner
          DOCKER_NAMESPACE: iteratec
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./cleaner/
  balancer:
    name: Balancer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build'n Push Balancer
        uses: pangzineng/Github-Action-One-Click-Docker@bfb4a810c8cb823f4a87c24da145caa707e297e9
        env:
          DOCKER_IMAGE_NAME: juice-balancer
          DOCKER_NAMESPACE: iteratec
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./juice-balancer/
